class Item < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'トップス' },
    { id: 3, name: 'ジャケット/アウター' },
    { id: 4, name: 'パンツ' },
    { id: 5, name: 'オールインワン・サロペット' },
    { id: 6, name: 'スカート' },
    { id: 7, name: 'ワンピース/ドレス' },
    { id: 8, name: 'フォーマルスーツ/小物' },
    { id: 9, name: 'バッグ' },
    { id: 10, name: 'シューズ' },
    { id: 11, name: 'ファッション雑貨' },
    { id: 12, name: '財布/小物' },
    { id: 13, name: '腕時計' },
    { id: 14, name: 'ヘアアクセサリー' },
    { id: 15, name: 'アクセサリー' },
    { id: 16, name: 'アンダーウェア' },
    { id: 17, name: 'レッグウェア' },
    { id: 18, name: 'ルームウェア' },
    { id: 19, name: '帽子' },
    { id: 20, name: '水着/着物・浴衣' },
    { id: 21, name: 'ママ&ベビー' },
    { id: 22, name: 'インテリア' },
    { id: 23, name: '食器/キッチン' },
    { id: 24, name: '雑貨/ホビー' },
    { id: 25, name: 'PC・スマホグッズ/家電' },
    { id: 26, name: 'スキンケア' },
    { id: 27, name: 'ベースメイク' },
    { id: 28, name: 'メイクアップ' },
    { id: 29, name: 'ビューティーグッズ' },
    { id: 30, name: 'ボディ・ヘアケア' },
    { id: 31, name: 'フレグランス' },
    { id: 32, name: 'アウトドア/スポーツ' },
    { id: 33, name: 'ペットグッズ' },
    { id: 34, name: '音楽/本・雑誌' },
    { id: 35, name: 'その他' },
  ]
  end